name: Build and E2E Tests

on:
  push:
    branches:
      # - '*'
      # apply to main only for now
      - 'main'
      - 'e2e/**'

jobs:
  fingerprint:
    image: latest
    outputs:
      fingerprint: ${{ steps.fingerprint_hash_step.outputs.fingerprint_hash }}
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: Install additional tools
        run: sudo apt-get update -y && sudo apt-get install -y jq
      - name: Set fingerprint variables
        id: fingerprint_hash_step
        run: |
          FINGERPRINT=$(npx expo-updates fingerprint:generate --platform ios)
          FINGERPRINT_HASH=$(echo $FINGERPRINT | jq -r '.hash')
          echo "Fingerprint hash: $FINGERPRINT_HASH"
          set-output fingerprint_hash $FINGERPRINT_HASH
      - name: Print fingerprint hash
        run: |
          echo "Fingerprint hash: ${ steps.fingerprint_hash_step.fingerprint_hash }"
  existing_build:
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.fingerprint_hash }}
  build:
    type: build
    needs: [existing_build]
    if: ${{ !needs.existing_build.outputs.build_id }}
    params:
      platform: ios
      profile: ios-simulator-preview
  end-to-end-test:
    after: [existing_build, build]
    type: maestro
    image: latest
    params:
      build_id: ${{ after.existing_build.outputs.build_id || after.build.outputs.build_id }}
      flow_path: ['./maestro/flow.yaml']
