name: Integrity Check

on:
  push:
    branches: ['*']

jobs:
  Test:
    type: custom
    steps:
      - name: upgrade pnpm
        run: npm i -g pnpm
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: Run test
        run: pnpm test
  Lint:
    type: custom
    steps:
      - name: upgrade pnpm
        run: npm i -g pnpm
      - name: eslint install
        run: npm i -g eslint@latest
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: eslint version
        run: npx eslint --version
      - name: Run lint 1
        run: pnpm eslint .
      - name: Run lint 2
        run: pnpm lint
