name: Integrity Check

on:
  push:
    branches: ['*']

jobs:
  Test:
    type: custom
    steps:
      - name: upgrade pnpm
        run: pnpm i -g pnpm
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: echo pwd
        run: pwd
      - name: echo ls
        run: ls
      - name: Run test
        run: pnpm turbo test
  Lint:
    type: custom
    steps:
      - name: upgrade pnpm
        run: pnpm i -g pnpm
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: Run lint
        run: pnpm turbo lint
