name: Integrity Check

on:
  push:
    branches: ['*']

jobs:
  Integrity Check:
    type: custom
    steps:
      - name: upgrade pnpm
        run: npm i -g pnpm
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: Run lint
        run: pnpm lint
      - name: Run test
        run: pnpm test
