name: Run Unit Tests

on:
  push:
    branches: ['*']

jobs:
  build:
    name: Build Android app
    steps:
      - name: upgrade pnpm
        run: npm i -g pnpm
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - eas/prebuild
      - eas/configure_eas_update
      - eas/inject_android_credentials
      - eas/run_gradle:
          inputs:
            command: :app:test