name: Run Unit Tests

on:
  push:
    branches: ['*']

jobs:
  build:
    name: Build Android app
    steps:
      - name: upgrade pnpm
        run: npm i -g pnpm
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - uses: eas/prebuild
      - uses: eas/configure_eas_update
      - uses: eas/inject_android_credentials
      - uses: eas/run_gradle
          with:
            command: :app:test