name: Run Unit Tests

on:
  push:
    branches: ['*']

jobs:
  Native Unit Test:
    type: custom
    steps:
      - name: upgrade pnpm
        run: npm i -g pnpm
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - uses: eas/prebuild
      - eas/run_gradle
          inputs:
            command: :app:bundleRelease