packages:
  - apps/*
  - libs/*
  - tools/*

catalog:
  "@tanstack/react-query": ^5.59.15
  "@types/jest": ^29.5.14
  eslint: ^9.12.0
  jest: ^29.7.0
  prettier: ^3.3.3
  typescript: ^5.6.3

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1

